bookstore_app/config/routes.rb
Rails.application.routes.draw do
  get 'novells/index'
  get 'novells/show'
  get 'novells/new'
  get 'novells/create'
  get 'novells/update'
  get 'novells/edit'
  get 'novells/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'genres/index'
  get 'genres/show'
  get 'genres/new'
  get 'genres/create'
  get 'genres/update'
  get 'genres/edit'
  get 'genres/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :books
  resources :authors
  resources :genres
  resources :publishers
  resources :novells
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookstore_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore_app/app/models/author.rb
class Author < ApplicationRecord
	has_many :novells
	validates :fname, presence: true
	validates :lname, presence: true
	validates :bio, presence: true
end

bookstore_app/app/models/book.rb
class Book < ApplicationRecord
end

bookstore_app/app/models/genre.rb
class Genre < ApplicationRecord
	has_many :novells
	validates :name, presence: true, length: {minimum: 3}
end

bookstore_app/app/models/novell.rb
class Novell < ApplicationRecord
	belongs_to :author
	belongs_to :genre
	belongs_to :publisher
end

bookstore_app/app/models/publisher.rb
class Publisher < ApplicationRecord
	has_many :novells
	validates :name, presence: true
	validates :country, presence: true
end

bookstore_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookstore_app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
	@authors=Author.all
  end

  def show
	@author = Author.find(params[:id])
  end

  def new
	@author = Author.new
  end
new
  def create
	@author = Author.new(author_params)
	if @author.save
		redirect_to authors_path
	else 
		render 'new'
	end
  end

  def update
  end

  def edit
  end

  def destroy
  end
  private 
  def author_params
	params.require(:author).permit(:fname, :lname, :bio)
  end
end

bookstore_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books=Book.all 
	end	
	def new
		
	end
	def show
		@book=Book.find(params[:id]) 
	end 
	def create
		#render plain: params[:book].inspect 
		@book=Book.new(book_params)
		@book.save
		redirect_to @book
	end
        private
	def book_params
		params.require(:book).permit(:title, :price, :book_id, :publisher, :description, :number)
	end
end

bookstore_app/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
	@genres=Genre.all
  end

  def show
	@genre = Genre.find(params[:id])
  end

  def new
	@genre = Genre.new
  end

  def create
	@genre = Genre.new(genre_params)
	if @genre.save
		redirect_to genres_path
	else 
		render 'new'
	end
  end

  def update
  end

  def edit
  end

  def destroy
  end
  private 
  def genre_params
	params.require(:genre).permit(:name)
  end
end

bookstore_app/app/controllers/novells_controller.rb
class NovellsController < ApplicationController
  def index
	@novells=Novell.all
  end

  def show
	@novell=Novell.find(params[:id])
  end

  def new
	@novell=Novell.new
	@genre=Genre.new
	@author=Author.new
	@publisher=Publisher.new
  end

  def create
	@novell = Novell.new(novell_params)
	if @novell.save
		redirect_to novells_path
	else 
		render 'new'
	end
  end

  def update
    @novell = Novell.find(params[:id])
    if @novell.update(novell_params)
      redirect_to @novell
    else 
      render 'edit'
    end
  end

  def edit
  @novell=Novell.find(params[:id])
  end

  def destroy
	@novell = Novell.find(params[:id])
	@novell.destroy
	redirect_to novells_path
  end
  private 
  def novell_params
	params.require(:novell).permit(:title, :genre_id, :author_id, :publisher_id, :isbn, :price, :publication, :format, :description, :pages)
  end
end

bookstore_app/app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
	@publishers=Publisher.all
  end

  def show
	@publisher=Publisher.find(params[:id])
  end

  def new
	@publisher=Publisher.new
  end

  def create
	@publisher = Publisher.new(publisher_params)
	if @publisher.save
		redirect_to publishers_path
	else 
		render 'new'
	end
  end

  def update
  end

  def edit
  end

  def destroy
  end
  private 
  def publisher_params
	params.require(:publisher).permit(:name, :country)
  end
end

bookstore_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

bookstore_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore_app/app/helpers/authors_helper.rb
module AuthorsHelper
end

bookstore_app/app/helpers/books_helper.rb
module BooksHelper
end

bookstore_app/app/helpers/genres_helper.rb
module GenresHelper
end

bookstore_app/app/helpers/novells_helper.rb
module NovellsHelper
end

bookstore_app/app/helpers/publishers_helper.rb
module PublishersHelper
end

bookstore_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bookstore_app/app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

bookstore_app/app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

bookstore_app/app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

bookstore_app/app/views/authors/index.html.erb
<div class="container">
	<h2>Authors Available</h2>
	<table border="1" class="table">
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Bio</th>
			<th>Author Page</th>
		</tr>
		<% @authors.each do |author| %>
		<tr>
			<td><%= author.fname %></td>
			<td><%= author.lname %></td>
			<td><%= author.bio %></td>
			<td><%= link_to 'Author Page', author_path(author) %></td>
		</tr>
		<% end %>
	</table>
</div>
			
	

bookstore_app/app/views/authors/new.html.erb
<div class="container">
	<h2>Add New Author</h2>
	<%= form_for :author, url: authors_path do |f| %>
	
	<div class="form-group">
		<%= f.label :fname %><br>
		<%= f.text_field :fname, class:'form-control' %><br>
	</div>

	<div class="form-group">
		<%= f.label :lname %><br>
		<%= f.text_field :lname, class:'form-control' %><br>
	</div>

	<div class="form-group">
		<%= f.label :bio %><br>
		<%= f.text_area :bio, class:'form-control' %><br>
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", authors_path, class:'btn btn-default' %>
	<% end %>
</div>

bookstore_app/app/views/authors/show.html.erb
<div class="container">

<h3>Author Details</h3>
<p>Author Name: <%= @author.fname %> </p>

<%= form_for :author, url: authors_path do |f| %>
	
	<div class="form-group">
		<%= f.label :fname %><br>
		<%= f.text_field :fname, class:'form-control' %><br>
	</div>

	<div class="form-group">
		<%= f.label :lname %><br>
		<%= f.text_field :lname, class:'form-control' %><br>
	</div>

	<div class="form-group">
		<%= f.label :bio %><br>
		<%= f.text_area :bio, class:'form-control' %><br>
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", authors_path, class:'btn btn-default' %>
	<% end %>
</div>

bookstore_app/app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

bookstore_app/app/views/books/index.html.erb
<div class="container">
	<h2>Books Available</h2>
	<table border="1" class="table">
		<tr>
			<th>Book Title</th>
			<th>Book Code</th>
			<th>Book Price</th>
			<th>Publisher</th>
			<th>Book Description</th>
			<th>Number of Copies</th>
			<th>Book Page</th>
		</tr>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.book_id %></td>
			<td><%= book.price %></td>
			<td><%= book.publisher %></td>
			<td><%= book.description %></td>
			<td><%= book.number %></td>
			<td><%= link_to 'Book Page', book_path(book) %></td>
		</tr>
		<% end %>
	</table>
</div>
			
	

bookstore_app/app/views/books/new.html.erb
<div class="container">
	<h1> Add New Book</h1>
	<%= form_for :book, url: books_path do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		<div class="form-group">
			<%= f.label :price %>
			<%= f.number_field :price %>
		</div>
		<div class="form-group">
			<%= f.label :book_id %>
			<%= f.text_field :book_id %>
		</div>
		<div class="form-group">
			<%= f.label :publisher %>
			<%= f.text_field :publisher %>
		</div>
		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description %>
		</div>
		<div class="form-group">
			<%= f.label :number %>
			<%= f.number_field :number %>
		</div>
		<div class="form-group">
			<%=f.submit %>
		</div>
	<% end %>
</div>

bookstore_app/app/views/books/show.html.erb
<div class="container">

<h3>Book Details</h3>
<p>Book Title: <%= @book.title %> </p>

<%= form_for :book, url: books_path do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title %>
		</div>
		<div class="form-group">
			<%= f.label :price %>
			<%= f.number_field :price %>
		</div>
		<div class="form-group">
			<%= f.label :book_id %>
			<%= f.text_field :book_id %>
		</div>
		<div class="form-group">
			<%= f.label :publisher %>
			<%= f.text_field :publisher %>
		</div>
		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description %>
		</div>
		<div class="form-group">
			<%= f.label :number %>
			<%= f.number_field :number %>
		</div>
		<div class="form-group">
			<%=f.submit %>
		</div>
	<% end %>
</div>

bookstore_app/app/views/genres/create.html.erb
<h1>Genres#create</h1>
<p>Find me in app/views/genres/create.html.erb</p>

bookstore_app/app/views/genres/destroy.html.erb
<h1>Genres#destroy</h1>
<p>Find me in app/views/genres/destroy.html.erb</p>

bookstore_app/app/views/genres/edit.html.erb
<h1>Genres#edit</h1>
<p>Find me in app/views/genres/edit.html.erb</p>

bookstore_app/app/views/genres/index.html.erb
<div class="container">
	<h2>Genres Available</h2>
	<table border="1" class="table">
		<tr>
			<th>Name</th>
			<th>Genre Page</th>
		</tr>
		<% @genres.each do |genre| %>
		<tr>
			<td><%= genre.name %></td>
			<td><%= link_to 'Genre Page', genre_path(genre) %></td>
		</tr>
		<% end %>
	</table>
</div>
			
	

bookstore_app/app/views/genres/new.html.erb
<div class="container">
	<h2>Add New Genre</h2>
	<%= form_for :genre, url: genres_path do |f| %>
	
	<div class="form-group">
		<%= f.label :name %><br>
		<%= f.text_field :name, class:'form-control' %><br>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", genres_path, class:'btn btn-default' %>
	<% end %>
</div>

bookstore_app/app/views/genres/show.html.erb
<div class="container">

<h3>Genre Details</h3>
<p>Genre Name: <%= @genre.name %> </p>

<%= form_for :genre, url: genres_path do |f| %>
	
	<div class="form-group">
		<%= f.label :name %><br>
		<%= f.text_field :name, class:'form-control' %><br>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", genres_path, class:'btn btn-default' %>
	<% end %>
</div>

bookstore_app/app/views/genres/update.html.erb
<h1>Genres#update</h1>
<p>Find me in app/views/genres/update.html.erb</p>

bookstore_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookstoreApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
          <h5 class="my-0 mr-md-auto font-weight-normal"> Sheffield Bookstore </h5>
          <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="#"><%=link_to "Home", '/' %></a>
            <a class="p-2 text-dark" href="#"><%=link_to "Novels", '../novells' %></a>
            <a class="p-2 text-dark" href="#"><%=link_to "Authors", '../authors' %></a>
	    <a class="p-2 text-dark" href="#"><%=link_to "Genres", '../genres' %></a>
	    <a class="p-2 text-dark" href="#"><%=link_to "Publishers", '../publishers' %></a>
          </nav>
        </div>
    <div class="container">
        <a class="btn btn-primary" href="../novells/new">Create Novels</a>
        <a class="btn btn-primary" href="../authors/new">Create Authors</a>
	<a class="btn btn-primary" href="../genres/new">Create Genres</a>
	<a class="btn btn-primary" href="../publishers/new">Create Publishers</a>
        <div style="padding-top:0.5rem"><%= yield %></div>
    </div>

  </body>
</html>

bookstore_app/app/views/novells/create.html.erb
<h1>Novells#create</h1>
<p>Find me in app/views/novells/create.html.erb</p>

bookstore_app/app/views/novells/destroy.html.erb
<h1>Novells#destroy</h1>
<p>Find me in app/views/novells/destroy.html.erb</p>

bookstore_app/app/views/novells/edit.html.erb
<div class="container">
	<h2>Edit New Novel</h2>
	<%= form_for @novell do |f| %>
	<div class="form-group">
		<%= f.label :title %><br />
		<%= f.text_field :title, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :isbn %><br />
		<%= f.text_field :isbn, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :format %><br />
		<%= f.text_field :format, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :genre %><br />
		<%= f.select :genre_id, Genre.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'},class:'form-control' %><br /><br />
</div>
	<div class="form-group">
		<%= f.label :publisher %><br />
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'},class:'form-control' %><br /><br />
	<div class="form-group">
		<%= f.label :author %><br>
		<%= f.select :author_id, Author.all.collect {|x| [x.fname + ' ' + x.lname, x.id]}, {:include_blank => 'Select Author'},class:'form-control' %><br /><br />
	</div>
	<div class="form-group">
		<%= f.label :price %><br />
		<%= f.text_field :price, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :pages %><br />
		<%= f.text_field :pages, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :publication %><br />
		<%= f.text_field :publication, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :description %><br />
		<%= f.text_field :description, class:'form-control' %><br />
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", novells_path, class:'btn btn-default' %>
	<% end %>
	</div>
</div>

bookstore_app/app/views/novells/index.html.erb
<div class="container">
	<h2>Novels Available</h2>
	<table borde="1" class="table">
	<tr>
		<th>Novel Title</th>
		<th>Author ID</th>
		<th>Publisher ID</th>
		<th>Genre ID</th>
		<th>Price</th>
		<th>ISBN</th>
		<th>Publication</th>
		<th>Pages</th>
		<th>Format</th>
		<th>Description</th>
		<th>Details</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<% @novells.each do |novell| %>
	<tr>
		<td><%= novell.title %></td>
		<td><%= novell.author_id %></td>
		<td><%= novell.publisher_id %></td>
		<td><%= novell.genre_id %></td>
		<td><%= novell.price %></td>
		<td><%= novell.isbn %></td>
		<td><%= novell.publication %></td>
		<td><%= novell.pages %></td>
		<td><%= novell.format %></td>
		<td><%= novell.description %></td>
		<td><%= link_to 'Show', novell_path(novell) %></td>
		<td><%= link_to 'Edit', edit_novell_path(novell) %></td>
		<td><%= link_to 'Delete', novell_path(novell), method: :Delete, data: {confirm: "Are you sure you want to delete details"} %></td>
	</tr>
	<% end %>
	</table>
</div>

bookstore_app/app/views/novells/new.html.erb
<div class="container">
	<h2>Add New Novel</h2>
	<%= form_for :novell, url: novells_path do |f| %>
	<div class="form-group">
		<%= f.label :title %><br />
		<%= f.text_field :title, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :isbn %><br />
		<%= f.text_field :isbn, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :format %><br />
		<%= f.text_field :format, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :genre %><br />
		<%= f.select :genre_id, Genre.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'},class:'form-control' %><br /><br />
</div>
	<div class="form-group">
		<%= f.label :publisher %><br />
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'},class:'form-control' %><br /><br />
	<div class="form-group">
		<%= f.label :author %><br>
		<%= f.select :author_id, Author.all.collect {|x| [x.fname + ' ' + x.lname, x.id]}, {:include_blank => 'Select Author'},class:'form-control' %><br /><br />
	</div>
	<div class="form-group">
		<%= f.label :price %><br />
		<%= f.text_field :price, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :pages %><br />
		<%= f.text_field :pages, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :publication %><br />
		<%= f.text_field :publication, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :description %><br />
		<%= f.text_field :description, class:'form-control' %><br />
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", novells_path, class:'btn btn-default' %>
	<% end %>
	</div>
</div>

bookstore_app/app/views/novells/show.html.erb
<div class="container">

<h3>Novel Details</h3>
<p>Novel Name: <%= @novell.title %> </p>

	<%= form_for :novell, url: novells_path do |f| %>
	<div class="form-group">
		<%= f.label :title %><br />
		<%= f.text_field :title, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :isbn %><br />
		<%= f.text_field :isbn, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :format %><br />
		<%= f.text_field :format, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :genre %><br />
		<%= f.select :genre_id, Genre.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'},class:'form-control' %><br /><br />
</div>
	<div class="form-group">
		<%= f.label :publisher %><br />
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select Genre'},class:'form-control' %><br /><br />
	<div class="form-group">
		<%= f.label :author %><br>
		<%= f.select :author_id, Author.all.collect {|x| [x.fname + ' ' + x.lname, x.id]}, {:include_blank => 'Select Author'},class:'form-control' %><br /><br />
	</div>
	<div class="form-group">
		<%= f.label :price %><br />
		<%= f.text_field :price, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :pages %><br />
		<%= f.text_field :pages, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :publication %><br />
		<%= f.text_field :publication, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :description %><br />
		<%= f.text_field :description, class:'form-control' %><br />
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", novells_path, class:'btn btn-default' %>
	<% end %>
	</div>
</div>

bookstore_app/app/views/novells/update.html.erb
<h1>Novells#update</h1>
<p>Find me in app/views/novells/update.html.erb</p>

bookstore_app/app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

bookstore_app/app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

bookstore_app/app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

bookstore_app/app/views/publishers/index.html.erb
<div class="container">
	<h2>Publishers Available</h2>
	<table border="1" class="table">
		<tr>
			<th>Name</th>
			<th>Country</th>
			<th>Genre Page</th>
		</tr>
		<% @publishers.each do |publisher| %>
		<tr>
			<td><%= publisher.name %></td>
			<td><%= publisher.country %></td>
			<td><%= link_to 'Publisher Page', publisher_path(publisher) %></td>
		</tr>
		<% end %>
	</table>
</div>
			
	

bookstore_app/app/views/publishers/new.html.erb
<div class="container">
	<h2>Add New Publisher</h2>
	<%= form_for :publisher, url: publishers_path do |f| %>
	
	<div class="form-group">
		<%= f.label :name %><br>
		<%= f.text_field :name, class:'form-control' %><br>
		<%= f.label :country %><br>
		<%= f.text_field :country, class:'form-control' %><br>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", publishers_path, class:'btn btn-default' %>
	<% end %>
</div>

bookstore_app/app/views/publishers/show.html.erb
<div class="container">

<h3>Publisher Details</h3>
<p>Publisher Name: <%= @publisher.name %> </p>

<%= form_for :publisher, url: publishers_path do |f| %>
	
	<div class="form-group">
		<%= f.label :name %><br>
		<%= f.text_field :name, class:'form-control' %><br>
     		<%= f.label :country %><br>
		<%= f.text_field :country, class:'form-control' %><br>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", publishers_path, class:'btn btn-default' %>
	<% end %>
</div>

bookstore_app/app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>

bookstore_app/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

bookstore_app/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

bookstore_app/app/views/static_pages/home.html.erb
<div class="container">
	<h1 class="jumbotron-heading">Album example</h1>
	<div class="container">
		<div class="row">
			<div class="col">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
			<div class="col">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			</div>
		</div>
	</div>